repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.3'  # Remplacez par la version souhaitée
    hooks:
      - id: ruff
        name: ruff-format
        args: ['--fix']
      - id: ruff
        name: ruff-lint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'  # Remplacez par la version souhaitée
    hooks:
      - id: mypy
